channels:
- conda-forge
dependencies:
- python=3.10.18
- pip<=25.2
- pip:
  - mlflow==3.4.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - psutil==7.1.0
  - scikit-learn==1.3.0
  - scipy==1.11.1
name: mlflow-env
